version: "3.9"
services:
  webapp:
    build:
      context: ./CG
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"